// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	User
	Item
	Interaction
	TargetUser
	TargetItem
	WrittenCSVInfo
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                        int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Jobroles                  []int32 `protobuf:"varint,2,rep,packed,name=jobroles" json:"jobroles,omitempty"`
	CareeLevel                int32   `protobuf:"varint,3,opt,name=caree_level,json=careeLevel" json:"caree_level,omitempty"`
	DisciplineId              int32   `protobuf:"varint,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId                int32   `protobuf:"varint,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country                   string  `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	Region                    int32   `protobuf:"varint,7,opt,name=region" json:"region,omitempty"`
	ExperienceNEntriesClass   int32   `protobuf:"varint,8,opt,name=experience_n_entries_class,json=experienceNEntriesClass" json:"experience_n_entries_class,omitempty"`
	ExperienceYearsExperience int32   `protobuf:"varint,9,opt,name=experience_years_experience,json=experienceYearsExperience" json:"experience_years_experience,omitempty"`
	ExperienceYearsInCurrent  int32   `protobuf:"varint,10,opt,name=experience_years_in_current,json=experienceYearsInCurrent" json:"experience_years_in_current,omitempty"`
	EduDegree                 int32   `protobuf:"varint,11,opt,name=edu_degree,json=eduDegree" json:"edu_degree,omitempty"`
	EduFieldofstudies         []int32 `protobuf:"varint,12,rep,packed,name=edu_fieldofstudies,json=eduFieldofstudies" json:"edu_fieldofstudies,omitempty"`
	Wtcj                      int32   `protobuf:"varint,13,opt,name=wtcj" json:"wtcj,omitempty"`
	Premium                   int32   `protobuf:"varint,14,opt,name=premium" json:"premium,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetJobroles() []int32 {
	if m != nil {
		return m.Jobroles
	}
	return nil
}

func (m *User) GetCareeLevel() int32 {
	if m != nil {
		return m.CareeLevel
	}
	return 0
}

func (m *User) GetDisciplineId() int32 {
	if m != nil {
		return m.DisciplineId
	}
	return 0
}

func (m *User) GetIndustryId() int32 {
	if m != nil {
		return m.IndustryId
	}
	return 0
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User) GetRegion() int32 {
	if m != nil {
		return m.Region
	}
	return 0
}

func (m *User) GetExperienceNEntriesClass() int32 {
	if m != nil {
		return m.ExperienceNEntriesClass
	}
	return 0
}

func (m *User) GetExperienceYearsExperience() int32 {
	if m != nil {
		return m.ExperienceYearsExperience
	}
	return 0
}

func (m *User) GetExperienceYearsInCurrent() int32 {
	if m != nil {
		return m.ExperienceYearsInCurrent
	}
	return 0
}

func (m *User) GetEduDegree() int32 {
	if m != nil {
		return m.EduDegree
	}
	return 0
}

func (m *User) GetEduFieldofstudies() []int32 {
	if m != nil {
		return m.EduFieldofstudies
	}
	return nil
}

func (m *User) GetWtcj() int32 {
	if m != nil {
		return m.Wtcj
	}
	return 0
}

func (m *User) GetPremium() int32 {
	if m != nil {
		return m.Premium
	}
	return 0
}

type Item struct {
	Id           int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title        int32   `protobuf:"varint,2,opt,name=title" json:"title,omitempty"`
	CareerLevel  int32   `protobuf:"varint,3,opt,name=career_level,json=careerLevel" json:"career_level,omitempty"`
	DisciplineId int32   `protobuf:"varint,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId   int32   `protobuf:"varint,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country      string  `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	IsPayed      int32   `protobuf:"varint,7,opt,name=is_payed,json=isPayed" json:"is_payed,omitempty"`
	Region       int32   `protobuf:"varint,8,opt,name=region" json:"region,omitempty"`
	Latitude     float32 `protobuf:"fixed32,9,opt,name=latitude" json:"latitude,omitempty"`
	Longitude    float32 `protobuf:"fixed32,10,opt,name=longitude" json:"longitude,omitempty"`
	Employment   int32   `protobuf:"varint,11,opt,name=employment" json:"employment,omitempty"`
	Tags         []int32 `protobuf:"varint,12,rep,packed,name=tags" json:"tags,omitempty"`
	CreatedAt    int64   `protobuf:"varint,13,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTitle() int32 {
	if m != nil {
		return m.Title
	}
	return 0
}

func (m *Item) GetCareerLevel() int32 {
	if m != nil {
		return m.CareerLevel
	}
	return 0
}

func (m *Item) GetDisciplineId() int32 {
	if m != nil {
		return m.DisciplineId
	}
	return 0
}

func (m *Item) GetIndustryId() int32 {
	if m != nil {
		return m.IndustryId
	}
	return 0
}

func (m *Item) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Item) GetIsPayed() int32 {
	if m != nil {
		return m.IsPayed
	}
	return 0
}

func (m *Item) GetRegion() int32 {
	if m != nil {
		return m.Region
	}
	return 0
}

func (m *Item) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Item) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Item) GetEmployment() int32 {
	if m != nil {
		return m.Employment
	}
	return 0
}

func (m *Item) GetTags() []int32 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Item) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Interaction struct {
	UserId          int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ItemId          int32 `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	InteractionType int32 `protobuf:"varint,3,opt,name=interaction_type,json=interactionType" json:"interaction_type,omitempty"`
	CreatedAt       int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Interaction) Reset()                    { *m = Interaction{} }
func (m *Interaction) String() string            { return proto.CompactTextString(m) }
func (*Interaction) ProtoMessage()               {}
func (*Interaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Interaction) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Interaction) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Interaction) GetInteractionType() int32 {
	if m != nil {
		return m.InteractionType
	}
	return 0
}

func (m *Interaction) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type TargetUser struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *TargetUser) Reset()                    { *m = TargetUser{} }
func (m *TargetUser) String() string            { return proto.CompactTextString(m) }
func (*TargetUser) ProtoMessage()               {}
func (*TargetUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TargetUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type TargetItem struct {
	ItemId int32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
}

func (m *TargetItem) Reset()                    { *m = TargetItem{} }
func (m *TargetItem) String() string            { return proto.CompactTextString(m) }
func (*TargetItem) ProtoMessage()               {}
func (*TargetItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TargetItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type WrittenCSVInfo struct {
	Filename   string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Filepath   string `protobuf:"bytes,2,opt,name=filepath" json:"filepath,omitempty"`
	RecordType string `protobuf:"bytes,3,opt,name=recordType" json:"recordType,omitempty"`
}

func (m *WrittenCSVInfo) Reset()                    { *m = WrittenCSVInfo{} }
func (m *WrittenCSVInfo) String() string            { return proto.CompactTextString(m) }
func (*WrittenCSVInfo) ProtoMessage()               {}
func (*WrittenCSVInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WrittenCSVInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *WrittenCSVInfo) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *WrittenCSVInfo) GetRecordType() string {
	if m != nil {
		return m.RecordType
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Interaction)(nil), "Interaction")
	proto.RegisterType((*TargetUser)(nil), "TargetUser")
	proto.RegisterType((*TargetItem)(nil), "TargetItem")
	proto.RegisterType((*WrittenCSVInfo)(nil), "WrittenCSVInfo")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0xd2, 0x7c, 0x79, 0xda, 0x06, 0x58, 0x21, 0xba, 0x2d, 0x5f, 0x25, 0x08, 0xa9, 0x1c,
	0xe0, 0xc2, 0x11, 0x81, 0x84, 0x4a, 0x91, 0x2c, 0x21, 0x84, 0x4c, 0x01, 0x71, 0xb2, 0x5c, 0xef,
	0x24, 0xdd, 0xca, 0x5e, 0x5b, 0xbb, 0x63, 0xc0, 0x67, 0x4e, 0xfc, 0x5a, 0xfe, 0x02, 0xda, 0x71,
	0x1c, 0xbb, 0x05, 0xae, 0xdc, 0xf6, 0xbd, 0x37, 0x33, 0x1a, 0xcf, 0x7b, 0x32, 0xcc, 0x4b, 0x5b,
	0x50, 0x91, 0x16, 0xd9, 0x53, 0x7e, 0x2c, 0x7e, 0x8c, 0x60, 0xf4, 0xd1, 0xa1, 0x15, 0x73, 0x18,
	0x6a, 0x25, 0x07, 0x87, 0x83, 0xa3, 0x71, 0x34, 0xd4, 0x4a, 0x1c, 0xc0, 0xec, 0xa2, 0x38, 0xb3,
	0x45, 0x86, 0x4e, 0x0e, 0x0f, 0xb7, 0x8e, 0xc6, 0xd1, 0x06, 0x8b, 0xfb, 0xb0, 0x9d, 0x26, 0x16,
	0x31, 0xce, 0xf0, 0x2b, 0x66, 0x72, 0x8b, 0x9b, 0x80, 0xa9, 0xb7, 0x9e, 0x11, 0x0f, 0x61, 0x57,
	0x69, 0x97, 0xea, 0x32, 0xd3, 0x06, 0x63, 0xad, 0xe4, 0x88, 0x4b, 0x76, 0x3a, 0x32, 0x54, 0x7e,
	0x8a, 0x36, 0xaa, 0x72, 0x64, 0x6b, 0x5f, 0x32, 0x6e, 0xa6, 0xb4, 0x54, 0xa8, 0x84, 0x84, 0x69,
	0x5a, 0x54, 0x86, 0x6c, 0x2d, 0x27, 0x87, 0x83, 0xa3, 0x20, 0x6a, 0xa1, 0xb8, 0x05, 0x13, 0x8b,
	0x2b, 0x5d, 0x18, 0x39, 0xe5, 0xae, 0x35, 0x12, 0xcf, 0xe1, 0x00, 0xbf, 0x97, 0x68, 0x35, 0x9a,
	0x14, 0x63, 0x13, 0xa3, 0x21, 0xab, 0xd1, 0xc5, 0x69, 0x96, 0x38, 0x27, 0x67, 0x5c, 0xbb, 0xd7,
	0x55, 0xbc, 0x3b, 0x69, 0xf4, 0x63, 0x2f, 0x8b, 0x97, 0x70, 0xbb, 0xd7, 0x5c, 0x63, 0x62, 0x5d,
	0xdc, 0x11, 0x32, 0xe0, 0xee, 0xfd, 0x8e, 0xf9, 0xe2, 0x2b, 0x4e, 0x36, 0x50, 0xbc, 0xf8, 0x4b,
	0xbf, 0x36, 0x71, 0x5a, 0x59, 0x8b, 0x86, 0x24, 0x70, 0xbf, 0xbc, 0xd2, 0x1f, 0x9a, 0xe3, 0x46,
	0x17, 0x77, 0x01, 0x50, 0x55, 0xb1, 0xc2, 0x95, 0x45, 0x94, 0xdb, 0x5c, 0x1d, 0xa0, 0xaa, 0x5e,
	0x33, 0x21, 0x9e, 0x80, 0xf0, 0xf2, 0x52, 0x63, 0xa6, 0x8a, 0xa5, 0xa3, 0x4a, 0x69, 0x74, 0x72,
	0x87, 0x9d, 0xb9, 0x81, 0xaa, 0x7a, 0x73, 0x49, 0x10, 0x02, 0x46, 0xdf, 0x28, 0xbd, 0x90, 0xbb,
	0x3c, 0x87, 0xdf, 0xfe, 0x9e, 0xa5, 0xc5, 0x5c, 0x57, 0xb9, 0x9c, 0x33, 0xdd, 0xc2, 0xc5, 0xaf,
	0x21, 0x8c, 0x42, 0xc2, 0xfc, 0x8f, 0x14, 0xdc, 0x84, 0x31, 0x69, 0xca, 0x50, 0x0e, 0x99, 0x6a,
	0x80, 0x78, 0x00, 0x3b, 0x6c, 0xb6, 0xbd, 0x14, 0x80, 0x26, 0x13, 0xf6, 0xff, 0x24, 0x60, 0x1f,
	0x66, 0xda, 0xc5, 0x65, 0x52, 0xa3, 0x5a, 0x67, 0x60, 0xaa, 0xdd, 0x7b, 0x0f, 0x7b, 0xe1, 0x98,
	0x5d, 0x0a, 0xc7, 0x01, 0xcc, 0xb2, 0x84, 0x34, 0x55, 0xaa, 0x31, 0x73, 0x18, 0x6d, 0xb0, 0xb8,
	0x03, 0x41, 0x56, 0x98, 0x55, 0x23, 0x02, 0x8b, 0x1d, 0x21, 0xee, 0x01, 0x60, 0x5e, 0x66, 0x45,
	0x9d, 0x7b, 0x23, 0x1b, 0x6b, 0x7a, 0x8c, 0x3f, 0x36, 0x25, 0xab, 0xd6, 0x0d, 0x7e, 0x7b, 0x3b,
	0x53, 0x8b, 0x09, 0xa1, 0x8a, 0x13, 0x62, 0x1b, 0xb6, 0xa2, 0x60, 0xcd, 0xbc, 0xa2, 0xc5, 0xcf,
	0x01, 0x6c, 0x87, 0x86, 0xd0, 0x26, 0x29, 0xf9, 0xe5, 0xf6, 0x60, 0x5a, 0x39, 0xb4, 0xf1, 0xe6,
	0xfa, 0x13, 0x0f, 0x43, 0xe5, 0x05, 0x4d, 0x98, 0x7b, 0xa1, 0xf1, 0x60, 0xe2, 0x61, 0xa8, 0xc4,
	0x63, 0xb8, 0xae, 0xbb, 0x01, 0x31, 0xd5, 0x25, 0xae, 0x8d, 0xb8, 0xd6, 0xe3, 0x4f, 0xeb, 0x12,
	0xaf, 0xec, 0x32, 0xba, 0xba, 0xcb, 0x23, 0x80, 0xd3, 0xc4, 0xae, 0x90, 0xf8, 0x47, 0xf0, 0xaf,
	0x4d, 0xba, 0x32, 0x4e, 0x4a, 0x6f, 0xaf, 0x41, 0x7f, 0xaf, 0xc5, 0x39, 0xcc, 0x3f, 0x5b, 0x4d,
	0x84, 0xe6, 0xf8, 0xc3, 0xa7, 0xd0, 0x2c, 0x0b, 0x7f, 0xf8, 0xa5, 0xce, 0xd0, 0x24, 0x39, 0x72,
	0x6d, 0x10, 0x6d, 0x70, 0xab, 0x95, 0x09, 0x9d, 0xf3, 0xf7, 0xad, 0x35, 0x8f, 0xfd, 0xd9, 0x2d,
	0xa6, 0x85, 0x55, 0xa7, 0xed, 0xb7, 0x05, 0x51, 0x8f, 0x39, 0x9b, 0xf0, 0x2f, 0xec, 0xd9, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x6f, 0x9f, 0x1e, 0xd4, 0x04, 0x00, 0x00,
}
