// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	User
	Item
	Interaction
	TargetUser
	TargetItem
	WrittenCSVInfo
	RawUser
	RawItem
	RawInteraction
	RawTargetUser
	RawTargetItem
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                        int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Jobroles                  []int32 `protobuf:"varint,2,rep,packed,name=jobroles" json:"jobroles,omitempty"`
	CareerLevel               int32   `protobuf:"varint,3,opt,name=career_level,json=careerLevel" json:"career_level,omitempty"`
	DisciplineId              int32   `protobuf:"varint,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId                int32   `protobuf:"varint,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country                   string  `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	Region                    int32   `protobuf:"varint,7,opt,name=region" json:"region,omitempty"`
	ExperienceNEntriesClass   int32   `protobuf:"varint,8,opt,name=experience_n_entries_class,json=experienceNEntriesClass" json:"experience_n_entries_class,omitempty"`
	ExperienceYearsExperience int32   `protobuf:"varint,9,opt,name=experience_years_experience,json=experienceYearsExperience" json:"experience_years_experience,omitempty"`
	ExperienceYearsInCurrent  int32   `protobuf:"varint,10,opt,name=experience_years_in_current,json=experienceYearsInCurrent" json:"experience_years_in_current,omitempty"`
	EduDegree                 int32   `protobuf:"varint,11,opt,name=edu_degree,json=eduDegree" json:"edu_degree,omitempty"`
	EduFieldofstudies         []int32 `protobuf:"varint,12,rep,packed,name=edu_fieldofstudies,json=eduFieldofstudies" json:"edu_fieldofstudies,omitempty"`
	Wtcj                      int32   `protobuf:"varint,13,opt,name=wtcj" json:"wtcj,omitempty"`
	Premium                   int32   `protobuf:"varint,14,opt,name=premium" json:"premium,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetJobroles() []int32 {
	if m != nil {
		return m.Jobroles
	}
	return nil
}

func (m *User) GetCareerLevel() int32 {
	if m != nil {
		return m.CareerLevel
	}
	return 0
}

func (m *User) GetDisciplineId() int32 {
	if m != nil {
		return m.DisciplineId
	}
	return 0
}

func (m *User) GetIndustryId() int32 {
	if m != nil {
		return m.IndustryId
	}
	return 0
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User) GetRegion() int32 {
	if m != nil {
		return m.Region
	}
	return 0
}

func (m *User) GetExperienceNEntriesClass() int32 {
	if m != nil {
		return m.ExperienceNEntriesClass
	}
	return 0
}

func (m *User) GetExperienceYearsExperience() int32 {
	if m != nil {
		return m.ExperienceYearsExperience
	}
	return 0
}

func (m *User) GetExperienceYearsInCurrent() int32 {
	if m != nil {
		return m.ExperienceYearsInCurrent
	}
	return 0
}

func (m *User) GetEduDegree() int32 {
	if m != nil {
		return m.EduDegree
	}
	return 0
}

func (m *User) GetEduFieldofstudies() []int32 {
	if m != nil {
		return m.EduFieldofstudies
	}
	return nil
}

func (m *User) GetWtcj() int32 {
	if m != nil {
		return m.Wtcj
	}
	return 0
}

func (m *User) GetPremium() int32 {
	if m != nil {
		return m.Premium
	}
	return 0
}

type Item struct {
	Id           int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title        int32   `protobuf:"varint,2,opt,name=title" json:"title,omitempty"`
	CareerLevel  int32   `protobuf:"varint,3,opt,name=career_level,json=careerLevel" json:"career_level,omitempty"`
	DisciplineId int32   `protobuf:"varint,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId   int32   `protobuf:"varint,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country      string  `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	IsPayed      int32   `protobuf:"varint,7,opt,name=is_payed,json=isPayed" json:"is_payed,omitempty"`
	Region       int32   `protobuf:"varint,8,opt,name=region" json:"region,omitempty"`
	Latitude     float32 `protobuf:"fixed32,9,opt,name=latitude" json:"latitude,omitempty"`
	Longitude    float32 `protobuf:"fixed32,10,opt,name=longitude" json:"longitude,omitempty"`
	Employment   int32   `protobuf:"varint,11,opt,name=employment" json:"employment,omitempty"`
	Tags         []int32 `protobuf:"varint,12,rep,packed,name=tags" json:"tags,omitempty"`
	CreatedAt    int64   `protobuf:"varint,13,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetTitle() int32 {
	if m != nil {
		return m.Title
	}
	return 0
}

func (m *Item) GetCareerLevel() int32 {
	if m != nil {
		return m.CareerLevel
	}
	return 0
}

func (m *Item) GetDisciplineId() int32 {
	if m != nil {
		return m.DisciplineId
	}
	return 0
}

func (m *Item) GetIndustryId() int32 {
	if m != nil {
		return m.IndustryId
	}
	return 0
}

func (m *Item) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Item) GetIsPayed() int32 {
	if m != nil {
		return m.IsPayed
	}
	return 0
}

func (m *Item) GetRegion() int32 {
	if m != nil {
		return m.Region
	}
	return 0
}

func (m *Item) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Item) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Item) GetEmployment() int32 {
	if m != nil {
		return m.Employment
	}
	return 0
}

func (m *Item) GetTags() []int32 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Item) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Interaction struct {
	UserId          int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ItemId          int32 `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	InteractionType int32 `protobuf:"varint,3,opt,name=interaction_type,json=interactionType" json:"interaction_type,omitempty"`
	CreatedAt       int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Interaction) Reset()                    { *m = Interaction{} }
func (m *Interaction) String() string            { return proto.CompactTextString(m) }
func (*Interaction) ProtoMessage()               {}
func (*Interaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Interaction) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Interaction) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Interaction) GetInteractionType() int32 {
	if m != nil {
		return m.InteractionType
	}
	return 0
}

func (m *Interaction) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type TargetUser struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *TargetUser) Reset()                    { *m = TargetUser{} }
func (m *TargetUser) String() string            { return proto.CompactTextString(m) }
func (*TargetUser) ProtoMessage()               {}
func (*TargetUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TargetUser) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type TargetItem struct {
	ItemId int32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
}

func (m *TargetItem) Reset()                    { *m = TargetItem{} }
func (m *TargetItem) String() string            { return proto.CompactTextString(m) }
func (*TargetItem) ProtoMessage()               {}
func (*TargetItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TargetItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type WrittenCSVInfo struct {
	Filename   string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Filepath   string `protobuf:"bytes,2,opt,name=filepath" json:"filepath,omitempty"`
	RecordType string `protobuf:"bytes,3,opt,name=recordType" json:"recordType,omitempty"`
}

func (m *WrittenCSVInfo) Reset()                    { *m = WrittenCSVInfo{} }
func (m *WrittenCSVInfo) String() string            { return proto.CompactTextString(m) }
func (*WrittenCSVInfo) ProtoMessage()               {}
func (*WrittenCSVInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WrittenCSVInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *WrittenCSVInfo) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *WrittenCSVInfo) GetRecordType() string {
	if m != nil {
		return m.RecordType
	}
	return ""
}

type RawUser struct {
	Id                        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Jobroles                  string `protobuf:"bytes,2,opt,name=jobroles" json:"jobroles,omitempty"`
	CareerLevel               string `protobuf:"bytes,3,opt,name=career_level,json=careerLevel" json:"career_level,omitempty"`
	DisciplineId              string `protobuf:"bytes,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId                string `protobuf:"bytes,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country                   string `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	Region                    string `protobuf:"bytes,7,opt,name=region" json:"region,omitempty"`
	ExperienceNEntriesClass   string `protobuf:"bytes,8,opt,name=experience_n_entries_class,json=experienceNEntriesClass" json:"experience_n_entries_class,omitempty"`
	ExperienceYearsExperience string `protobuf:"bytes,9,opt,name=experience_years_experience,json=experienceYearsExperience" json:"experience_years_experience,omitempty"`
	ExperienceYearsInCurrent  string `protobuf:"bytes,10,opt,name=experience_years_in_current,json=experienceYearsInCurrent" json:"experience_years_in_current,omitempty"`
	EduDegree                 string `protobuf:"bytes,11,opt,name=edu_degree,json=eduDegree" json:"edu_degree,omitempty"`
	EduFieldofstudies         string `protobuf:"bytes,12,opt,name=edu_fieldofstudies,json=eduFieldofstudies" json:"edu_fieldofstudies,omitempty"`
	Wtcj                      string `protobuf:"bytes,13,opt,name=wtcj" json:"wtcj,omitempty"`
	Premium                   string `protobuf:"bytes,14,opt,name=premium" json:"premium,omitempty"`
}

func (m *RawUser) Reset()                    { *m = RawUser{} }
func (m *RawUser) String() string            { return proto.CompactTextString(m) }
func (*RawUser) ProtoMessage()               {}
func (*RawUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RawUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RawUser) GetJobroles() string {
	if m != nil {
		return m.Jobroles
	}
	return ""
}

func (m *RawUser) GetCareerLevel() string {
	if m != nil {
		return m.CareerLevel
	}
	return ""
}

func (m *RawUser) GetDisciplineId() string {
	if m != nil {
		return m.DisciplineId
	}
	return ""
}

func (m *RawUser) GetIndustryId() string {
	if m != nil {
		return m.IndustryId
	}
	return ""
}

func (m *RawUser) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RawUser) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *RawUser) GetExperienceNEntriesClass() string {
	if m != nil {
		return m.ExperienceNEntriesClass
	}
	return ""
}

func (m *RawUser) GetExperienceYearsExperience() string {
	if m != nil {
		return m.ExperienceYearsExperience
	}
	return ""
}

func (m *RawUser) GetExperienceYearsInCurrent() string {
	if m != nil {
		return m.ExperienceYearsInCurrent
	}
	return ""
}

func (m *RawUser) GetEduDegree() string {
	if m != nil {
		return m.EduDegree
	}
	return ""
}

func (m *RawUser) GetEduFieldofstudies() string {
	if m != nil {
		return m.EduFieldofstudies
	}
	return ""
}

func (m *RawUser) GetWtcj() string {
	if m != nil {
		return m.Wtcj
	}
	return ""
}

func (m *RawUser) GetPremium() string {
	if m != nil {
		return m.Premium
	}
	return ""
}

type RawItem struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	CareerLevel  string `protobuf:"bytes,3,opt,name=career_level,json=careerLevel" json:"career_level,omitempty"`
	DisciplineId string `protobuf:"bytes,4,opt,name=discipline_id,json=disciplineId" json:"discipline_id,omitempty"`
	IndustryId   string `protobuf:"bytes,5,opt,name=industry_id,json=industryId" json:"industry_id,omitempty"`
	Country      string `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
	IsPayed      string `protobuf:"bytes,7,opt,name=is_payed,json=isPayed" json:"is_payed,omitempty"`
	Region       string `protobuf:"bytes,8,opt,name=region" json:"region,omitempty"`
	Latitude     string `protobuf:"bytes,9,opt,name=latitude" json:"latitude,omitempty"`
	Longitude    string `protobuf:"bytes,10,opt,name=longitude" json:"longitude,omitempty"`
	Employment   string `protobuf:"bytes,11,opt,name=employment" json:"employment,omitempty"`
	Tags         string `protobuf:"bytes,12,opt,name=tags" json:"tags,omitempty"`
	CreatedAt    string `protobuf:"bytes,13,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *RawItem) Reset()                    { *m = RawItem{} }
func (m *RawItem) String() string            { return proto.CompactTextString(m) }
func (*RawItem) ProtoMessage()               {}
func (*RawItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RawItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RawItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RawItem) GetCareerLevel() string {
	if m != nil {
		return m.CareerLevel
	}
	return ""
}

func (m *RawItem) GetDisciplineId() string {
	if m != nil {
		return m.DisciplineId
	}
	return ""
}

func (m *RawItem) GetIndustryId() string {
	if m != nil {
		return m.IndustryId
	}
	return ""
}

func (m *RawItem) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RawItem) GetIsPayed() string {
	if m != nil {
		return m.IsPayed
	}
	return ""
}

func (m *RawItem) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *RawItem) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *RawItem) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *RawItem) GetEmployment() string {
	if m != nil {
		return m.Employment
	}
	return ""
}

func (m *RawItem) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *RawItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type RawInteraction struct {
	UserId          string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ItemId          string `protobuf:"bytes,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	InteractionType string `protobuf:"bytes,3,opt,name=interaction_type,json=interactionType" json:"interaction_type,omitempty"`
	CreatedAt       string `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *RawInteraction) Reset()                    { *m = RawInteraction{} }
func (m *RawInteraction) String() string            { return proto.CompactTextString(m) }
func (*RawInteraction) ProtoMessage()               {}
func (*RawInteraction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RawInteraction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RawInteraction) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *RawInteraction) GetInteractionType() string {
	if m != nil {
		return m.InteractionType
	}
	return ""
}

func (m *RawInteraction) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type RawTargetUser struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *RawTargetUser) Reset()                    { *m = RawTargetUser{} }
func (m *RawTargetUser) String() string            { return proto.CompactTextString(m) }
func (*RawTargetUser) ProtoMessage()               {}
func (*RawTargetUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RawTargetUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RawTargetItem struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
}

func (m *RawTargetItem) Reset()                    { *m = RawTargetItem{} }
func (m *RawTargetItem) String() string            { return proto.CompactTextString(m) }
func (*RawTargetItem) ProtoMessage()               {}
func (*RawTargetItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RawTargetItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Interaction)(nil), "Interaction")
	proto.RegisterType((*TargetUser)(nil), "TargetUser")
	proto.RegisterType((*TargetItem)(nil), "TargetItem")
	proto.RegisterType((*WrittenCSVInfo)(nil), "WrittenCSVInfo")
	proto.RegisterType((*RawUser)(nil), "RawUser")
	proto.RegisterType((*RawItem)(nil), "RawItem")
	proto.RegisterType((*RawInteraction)(nil), "RawInteraction")
	proto.RegisterType((*RawTargetUser)(nil), "RawTargetUser")
	proto.RegisterType((*RawTargetItem)(nil), "RawTargetItem")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0x6f, 0x6b, 0x13, 0x4f,
	0x10, 0xc7, 0x49, 0x9a, 0x7f, 0x33, 0x69, 0xf3, 0xfb, 0xb9, 0x88, 0xdd, 0xd6, 0x7f, 0x35, 0x22,
	0xc4, 0x07, 0xfa, 0xc4, 0x87, 0xa2, 0x20, 0xb5, 0xc2, 0x81, 0x88, 0x9c, 0x55, 0xf1, 0xd1, 0x71,
	0xbd, 0x9d, 0xa4, 0x5b, 0x2e, 0x77, 0xc7, 0xde, 0x9e, 0x35, 0x2f, 0x40, 0x50, 0xf0, 0xbd, 0x0a,
	0xbe, 0x02, 0xd9, 0xbd, 0x24, 0x77, 0x49, 0x73, 0x69, 0x6b, 0x41, 0x7c, 0x76, 0xdf, 0xef, 0xcc,
	0x2c, 0x93, 0x99, 0xe1, 0x43, 0xb0, 0x97, 0xa8, 0x58, 0xc7, 0x41, 0x1c, 0x3e, 0xb6, 0x1f, 0xfd,
	0xaf, 0x0d, 0x6c, 0xbc, 0x4f, 0x49, 0xb1, 0x1e, 0xd6, 0xa5, 0xe0, 0xb5, 0xbd, 0xda, 0xa0, 0xe9,
	0xd6, 0xa5, 0x60, 0xbb, 0xd8, 0x39, 0x89, 0x8f, 0x54, 0x1c, 0x52, 0xca, 0xeb, 0x7b, 0x1b, 0x83,
	0xa6, 0x3b, 0xd7, 0xec, 0x1e, 0x6e, 0x06, 0xbe, 0x22, 0x52, 0x5e, 0x48, 0x9f, 0x29, 0xe4, 0x1b,
	0xb6, 0xaa, 0x9b, 0x7b, 0xaf, 0x8d, 0xc5, 0xee, 0xe3, 0x96, 0x90, 0x69, 0x20, 0x93, 0x50, 0x46,
	0xe4, 0x49, 0xc1, 0x1b, 0x36, 0x67, 0xb3, 0x30, 0x1d, 0xc1, 0xee, 0x62, 0x57, 0x46, 0x22, 0x4b,
	0xb5, 0x9a, 0x98, 0x94, 0xa6, 0x4d, 0xc1, 0x99, 0xe5, 0x08, 0xc6, 0xb1, 0x1d, 0xc4, 0x59, 0xa4,
	0xd5, 0x84, 0xb7, 0xf6, 0x6a, 0x03, 0x70, 0x67, 0x92, 0xdd, 0xc0, 0x96, 0xa2, 0x91, 0x8c, 0x23,
	0xde, 0xb6, 0x55, 0x53, 0xc5, 0x9e, 0xe2, 0x2e, 0x7d, 0x49, 0x48, 0x49, 0x8a, 0x02, 0xf2, 0x22,
	0x8f, 0x22, 0xad, 0x24, 0xa5, 0x5e, 0x10, 0xfa, 0x69, 0xca, 0x3b, 0x36, 0x77, 0xbb, 0xc8, 0x78,
	0x73, 0x90, 0xc7, 0xf7, 0x4d, 0x98, 0x3d, 0xc7, 0x9b, 0xa5, 0xe2, 0x09, 0xf9, 0x2a, 0xf5, 0x0a,
	0x83, 0x83, 0xad, 0xde, 0x29, 0x9c, 0x4f, 0x26, 0xe3, 0x60, 0x2e, 0xd9, 0xb3, 0x15, 0xf5, 0x32,
	0xf2, 0x82, 0x4c, 0x29, 0x8a, 0x34, 0x47, 0x5b, 0xcf, 0x97, 0xea, 0x9d, 0x68, 0x3f, 0x8f, 0xb3,
	0xdb, 0x88, 0x24, 0x32, 0x4f, 0xd0, 0x48, 0x11, 0xf1, 0xae, 0xcd, 0x06, 0x12, 0xd9, 0x4b, 0x6b,
	0xb0, 0x47, 0xc8, 0x4c, 0x78, 0x28, 0x29, 0x14, 0xf1, 0x30, 0xd5, 0x99, 0x90, 0x94, 0xf2, 0x4d,
	0xbb, 0x9b, 0x6b, 0x24, 0xb2, 0x57, 0x0b, 0x01, 0xc6, 0xb0, 0x71, 0xaa, 0x83, 0x13, 0xbe, 0x65,
	0xdf, 0xb1, 0xdf, 0x66, 0x9e, 0x89, 0xa2, 0xb1, 0xcc, 0xc6, 0xbc, 0x67, 0xed, 0x99, 0xec, 0xff,
	0xac, 0x63, 0xc3, 0xd1, 0x34, 0x3e, 0x73, 0x07, 0xd7, 0xb1, 0xa9, 0xa5, 0x0e, 0x89, 0xd7, 0xad,
	0x95, 0x8b, 0x7f, 0xe1, 0x02, 0x76, 0xb0, 0x23, 0x53, 0x2f, 0xf1, 0x27, 0x24, 0xa6, 0x37, 0xd0,
	0x96, 0xe9, 0x5b, 0x23, 0x4b, 0xc7, 0xd1, 0x59, 0x38, 0x8e, 0x5d, 0xec, 0x84, 0xbe, 0x96, 0x3a,
	0x13, 0xf9, 0x32, 0xeb, 0xee, 0x5c, 0xb3, 0x5b, 0x08, 0x61, 0x1c, 0x8d, 0xf2, 0x20, 0xda, 0x60,
	0x61, 0xb0, 0x3b, 0x88, 0x34, 0x4e, 0xc2, 0x78, 0x32, 0x36, 0x8b, 0xcc, 0x57, 0x53, 0x72, 0xcc,
	0xb0, 0xb5, 0x3f, 0x9a, 0x6d, 0xc3, 0x7e, 0x9b, 0x75, 0x06, 0x8a, 0x7c, 0x4d, 0xc2, 0xf3, 0xb5,
	0x5d, 0xc3, 0x86, 0x0b, 0x53, 0xe7, 0x85, 0xee, 0x7f, 0xaf, 0x61, 0xd7, 0x89, 0x34, 0x29, 0x3f,
	0xd0, 0xa6, 0xb9, 0x6d, 0x6c, 0x67, 0x29, 0x29, 0x6f, 0x3e, 0xfd, 0x96, 0x91, 0x8e, 0x30, 0x01,
	0xa9, 0x69, 0x6c, 0x02, 0xf9, 0x0e, 0x5a, 0x46, 0x3a, 0x82, 0x3d, 0xc4, 0xff, 0x65, 0xf1, 0x80,
	0xa7, 0x27, 0x09, 0x4d, 0x17, 0xf1, 0x5f, 0xc9, 0x3f, 0x9c, 0x24, 0xb4, 0xd4, 0x4b, 0x63, 0xb9,
	0x97, 0x07, 0x88, 0x87, 0xbe, 0x1a, 0x91, 0xb6, 0x28, 0xa8, 0xea, 0xa4, 0x48, 0xb3, 0x97, 0x52,
	0xea, 0xab, 0x56, 0xee, 0xab, 0x7f, 0x8c, 0xbd, 0x8f, 0x4a, 0x6a, 0x4d, 0xd1, 0xfe, 0xbb, 0x0f,
	0x4e, 0x34, 0x8c, 0xcd, 0xe0, 0x87, 0x32, 0xa4, 0xc8, 0x1f, 0x93, 0xcd, 0x05, 0x77, 0xae, 0x67,
	0xb1, 0xc4, 0xd7, 0xc7, 0xf6, 0xf7, 0x4d, 0x63, 0x46, 0x9b, 0xb1, 0x2b, 0x0a, 0x62, 0x25, 0x0e,
	0x67, 0xbf, 0x0d, 0xdc, 0x92, 0xd3, 0xff, 0xd6, 0xc0, 0xb6, 0xeb, 0x9f, 0x2e, 0x01, 0x0c, 0x56,
	0x00, 0xcc, 0xbe, 0xbb, 0x16, 0x60, 0x70, 0x81, 0xf3, 0x85, 0xf3, 0xcf, 0x17, 0xfe, 0x08, 0x60,
	0x70, 0x09, 0x80, 0xc1, 0x95, 0x00, 0x06, 0x57, 0x04, 0x18, 0x5c, 0x0a, 0x60, 0x70, 0x11, 0x80,
	0x99, 0xb4, 0x73, 0x00, 0x06, 0xab, 0x01, 0x06, 0x05, 0xc0, 0x7e, 0xd5, 0xed, 0x29, 0x2c, 0x31,
	0x0c, 0xce, 0x32, 0x0c, 0xd6, 0x31, 0xec, 0x2f, 0x1f, 0xc1, 0x32, 0xc3, 0xa0, 0x8a, 0x61, 0x50,
	0xc9, 0x30, 0x58, 0xc7, 0x30, 0x58, 0xcf, 0x30, 0xa8, 0x60, 0x98, 0x9d, 0x77, 0x05, 0xc3, 0xa0,
	0xcc, 0x8d, 0x1f, 0x35, 0xec, 0x99, 0xa1, 0x57, 0x63, 0x0c, 0xaa, 0x30, 0x06, 0xe7, 0x62, 0x0c,
	0x2e, 0x82, 0xb1, 0x85, 0x76, 0x06, 0xb8, 0xe5, 0xfa, 0xa7, 0xd5, 0x24, 0x9b, 0x37, 0xb3, 0x90,
	0xb9, 0x0a, 0x66, 0xf3, 0xee, 0x8e, 0x5a, 0xf6, 0x7f, 0xd2, 0x93, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0xd8, 0xf3, 0x66, 0x39, 0x09, 0x00, 0x00,
}
